### PR TITLE
fix: Glance definitions when LSP return a location

### LINKED ISSUE #4: `Glance definitions` not work when LSP return a single `Location`
The command `Glance definitions` not work when LSP return a single [`Location`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#location)

https://user-images.githubusercontent.com/16160544/203999299-6485addc-32ef-4ea7-a9c9-65c6dffa6808.mp4

Thanks for this plugin!!!

### PR DESCRIPTION
**Pull request by aspeddro**
Close #4

### CODE REVIEW

File: lua/glance/lsp.lua [hunk 1]
```diff
@@ -8,8 +8,7 @@ local function create_handler(method)
       bufnr,
       method.lsp_method,
       params,
-      function(err, m, results)
-        results = method.lsp_method == m and results or m
+      function(err, result, _)
```
Comment (aspeddro) [inline lua/glance/lsp.lua:11]: The handler parameters is `err`, `result`, `ctx` and `config`. See [location handler](https://github.com/neovim/neovim/blob/29b80f6f2e9391b5d78390f65d09f00f73829310/runtime/lua/vim/lsp/handlers.lua#L359-L389)

File: lua/glance/lsp.lua [hunk 2]
```diff
@@ -19,16 +18,17 @@ local function create_handler(method)
           )
           return handler({})
         end
-        if results == nil or #results == 0 then
+        if result == nil or vim.tbl_isempty(result) then
```
Comment (aspeddro) [inline lua/glance/lsp.lua:21]: When LSP return a single Location, `#results` return zero, but in truth is one. See [https://stackoverflow.com/a/10755309](https://stackoverflow.com/a/10755309).

The Neovim core use [`vim.tbl_is_empty`](https://github.com/neovim/neovim/blob/29b80f6f2e9391b5d78390f65d09f00f73829310/runtime/lua/vim/lsp/handlers.lua#L360) to check if a table is empty.

**Comment by DNLHC** [comment]
Thank you!
